# Generated by Django 2.2.19 on 2023-01-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20230116_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.TextField(),
        ),
    ]
