# Generated by Django 2.2.16 on 2023-03-10 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20230310_1203'),
        ('posts', '0005_auto_20230310_1141'),
    ]

    operations = [
    ]
