# Generated by Django 2.2.16 on 2023-03-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20230309_1310'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_members',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_members'),
        ),
    ]
